# Generated by Django 3.1.1 on 2021-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210714_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='asset_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='assets',
            field=models.ManyToManyField(to='stock.Asset'),
        ),
    ]
