# Generated by Django 3.1.1 on 2021-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210719_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assets',
            field=models.ManyToManyField(null=True, to='stock.Asset'),
        ),
    ]
