# Generated by Django 3.1.1 on 2021-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_remove_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
