# Generated by Django 3.1.1 on 2021-08-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_member_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
